services:
  db:
    image: mariadb:10.5
    container_name: db
    ports:
      - '3308:3306'
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_USER: local
      MYSQL_PASSWORD: local
      MYSQL_DATABASE: local
      MYSQL_ROOT_PASSWORD: local

  node:
    image: arm64v8/node:23
    container_name: node-cmd
    volumes:
      - ./frontend:/app

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app

volumes:
  db:
  frontend:
