services:
  db:
    image: mariadb:10.5
    container_name: db
    ports:
      - "3308:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_USER: local
      MYSQL_PASSWORD: local
      MYSQL_DATABASE: local
      MYSQL_ROOT_PASSWORD: local

  frontend:
    build: 
      context: ./frontend
      target: dev
    container_name: frontend
    ports:
      - "3000:3000"
    develop:
      watch:
        - path: ./frontend
          action: sync
          target: /app
          ignore:
            - node_modules/

volumes:
  db:
